org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.5

# Fabric API
fabric_version=0.103.0+1.21.1

# Mod Properties
mod_version=1.0.0+mc1.21.1
maven_group=com.litematicastripper
archives_base_name=[\u6295\u5f71\u5265\u79bb] litematica-stripper
